channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.2
- pip:
  - mlflow==2.21.3
  - cffi==1.17.1
  - cloudpickle==3.1.0
  - defusedxml==0.7.1
  - lightgbm==4.6.0
  - matplotlib==3.9.0
  - numpy==1.26.4
  - pandas==2.2.0
  - psutil==5.9.0
  - pyarrow==18.0.0
  - scikit-learn==1.5.2
  - scipy==1.13.1
name: mlflow-env
